name: movie_booking
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  carousel_slider:
  curved_navigation_bar:
  intl: 
  firebase_core: 
  firebase_auth: 
  cloud_firestore: 
  firebase_messaging: 
  firebase_storage: 
  firebase_app_check: 
  random_string:
  shared_preferences:
  flutter_stripe: 
  http: 
  qr_flutter:
  mobile_scanner:
  provider: 
  image_picker:
  url_launcher:

dev_dependencies:
  flutter_launcher_icons: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  image_path: "images/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700