platform :ios, '12.0'

target 'Runner' do
  use_frameworks!

  # Add Firebase dependencies here
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'

  # Other dependencies can be added as needed
end
